### ISSUE TITLE
请问为什么斜切矩阵要这样表示

### ISSUE THREAD

**Issue by jing-jiu** [HYCS09/canvas-rendering-engine#3]
https://github.com/HYCS09/canvas-rendering-engine/blob/f143714b3e69a184e3be968c73871758f18906b1/src/lib/math/Transform.ts#L51
如这行注释所示，我所了解到的斜切应该是这样？  我的线代不是很好 没明白为什么可以转换成sin cos的形式 可以解答我的疑惑吗
```ts
/**
 * 斜切变换矩阵
 *
 * | 1         tan(skewX)  0 |   <- X轴方向上的斜切
 * | tan(skewY)  1         0 |   <- Y轴方向上的斜切
 * | 0           0         1 |
 *
 * 其中，skewX 和 skewY 是X轴和Y轴方向上的斜切角度（以弧度为单位）。
 */
 ```

**Comment by HYCS09** [comment]
你这种斜切变换是没问题的，浏览器的斜切变换就是你这样的，但是我这里的斜切采用了和pixi一样的斜切。可以看一下我的这篇文章：https://juejin.cn/post/7323398442729848869#heading-32

**Comment by HYCS09** [comment]
你这种斜切变换是没问题的，浏览器的斜切变换就是你这样的，但是我这里的斜切采用了和pixi一样的斜切。可以看一下我的这篇文章：https://juejin.cn/post/7323398442729848869#heading-32

**Comment by jing-jiu** [comment]
看完老哥的文章明白了  多谢
